config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: %i[index show]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/my_news_item/search' => 'my_news_items#search',
            :as                                                    => :search_my_news_item
        # match '/my_news_item/search', to:  'my_news_items#search',
        #                                                             via: [:post]
        # match '/my_news_item/search', to:  'my_news_items#save',
        #                                                             via: [:put]
        get '/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
                                                                    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    
    resources :news_items do
      collection do
        get :search
        post :create
      end
    end
  end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

class MyNewsItemsController < SessionController
  before_action :set_representative
  before_action :set_representatives_list
  before_action :set_news_item, only: %i[edit update destroy]
  before_action :set_issues_list

  def new
    @news_item = NewsItem.new
  end

  def edit; end

  def create
    puts
    @news_item = NewsItem.new(
      title:             params[:title],
      link:              params[:link],
      description:       params[:description],
      issue:             params[:issue],
      representative_id: @representative.id
    )
    if @news_item.save
      Rails.logger.debug { "33333333333333#{params}" }
      @news_item.ratings.create(user: @current_user, score: params[:rating].to_i)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  # sets selected rep and issue from view 1
  # queries articles
  def search
    @news_item = NewsItem.new
    @representative = Representative.find(params[:representative_id])
    @issue = params[:issue]
    @articles = NewsItem.get_articles(@representative.name, @issue)

    @news_items = @articles.map do |article|
      NewsItem.new do |news|
        news.title = article[:title]
        news.link = article[:url]
        news.description = article[:description]
        news.representative_id = @representative.id
        news.issue = @issue
      end
    end

    return unless @news_items.empty?

    flash.now[:error] = 'No news items available related to this issue'
    render :new
  end

  def create_rating
    @news_item = NewsItem.find(params[:id])
    if Rating.exists?(user: @current_user, news_item: @news_item)
      render json: { error: 'You have already rated this news item' }, status: :unprocessable_entity
    else
      @news_item.ratings.create!(user: @current_user, score: params[:rating].to_i)
      render json: { message: 'Rating created' }, status: :created
    end
  end

  # TODO: save selected news article to database
  def save; end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  def set_issues_list
    @issues_list = NewsItem::ISSUES_LIST
  end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :description, :link, :representative_id, :issue)
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :description, class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/_form_edit.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :description, class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, 'Issue', class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: true }, class: 'form-control'

    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/_form_search.html.haml
= form_with url: form_url, html: { method: form_method } do |f|
    = render 'issue_select', issues_list: issues_list
    .actions
        = f.submit 'Search', class: 'btn btn-primary'

app/views/my_news_items/_issue_select.html.haml
.form-group.row
    .col-sm-2
        = label :issue, 'Issue', class: 'col-form-label'
    .col-sm-10
        = select nil, :issue, issues_list, { include_blank: false }, class: 'form-control'

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form_edit', news_item: @news_item,
        form_url: representative_edit_my_news_item_path(@representative, @news_item),
        form_method: puts,
        representatives_list: @representatives_list,
        issues_list: @issues_list

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_item_path(@news_item), class: 'mx-1 btn btn-info' do
                    Show article
                    %i.fas.fa-eye
                = link_to representative_news_items_path(@representative), class: 'mx-1 btn btn-info' do
                    View all news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        Edit News Item for #{link_to @representative.name, representative_path(@representative.id)}

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form_search', news_item: @news_item,
        form_url: representative_search_my_news_item_path(@representative),
        form_method: :get,
        representatives_list: @representatives_list,
        issues_list: @issues_list

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_items_path(@representative), class: 'btn btn-info' do
                    View news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new_2.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit News Item

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_items_path(@representative), class: 'btn btn-info' do
                    View news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/search.html.haml
- rating_options = [['5 very good', 5], ['4 good', 4], ['3 normal', 3], ['2 bad', 2], ['1 very bad', 1]]

.row.mt-2
  .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
    Edit News Item
    = link_to @representative.name, representative_path(@representative.id)

  .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
    %span.issue-label Issue:
    = @issue
    %br/
    %br/

  = form_with(url: representative_my_news_item_new_path(@representative), local: true) do |form|
    - @news_items.each_with_index do |article, index|
      .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4.article
        %label
          = form.radio_button :selected_article, index, class: 'article-selector', checked: index.zero?
        %span.title-label Title:
        %span.title= article[:title]
        %br/
        %span.link-label Link:
        %a.link{ href: article[:link], target: '_blank' }= article[:link]
        %br/
        %span.description-label Description:
        %span.description= article[:description]
        %br/

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
      %label{ for: 'rating-dropdown' } Rating:
      = form.select :rating, options_for_select(rating_options)

    = form.hidden_field :title, id: 'hidden_title', value: @news_items[0][:title]
    = form.hidden_field :link, id: 'hidden_link', value: @news_items[0][:link]
    = form.hidden_field :description, id: 'hidden_description', value: @news_items[0][:description]
    = form.hidden_field :issue, id: 'hidden_issue', value: @issue


    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
      .clearfix.mt-3
        .float-right
          = link_to representative_news_items_path(@representative), class: 'btn btn-info' do
            View news articles
            %i.fas.fa-arrow-right
        .float-left
          = form.submit 'Save', class: 'btn btn-info'

:javascript
  document.addEventListener('DOMContentLoaded', function () {
    const articleSelectors = document.querySelectorAll('.article-selector');

    articleSelectors.forEach(function (radioButton) {
      radioButton.addEventListener('change', function (e) {
        if (e.target.checked) {
          const articleDiv = e.target.closest('.article');
          updateHiddenFields(articleDiv);
        }
      });
    });

    function updateHiddenFields(articleDiv) {
      const titleElement = articleDiv.querySelector('.title');
      const linkElement = articleDiv.querySelector('.link');
      const descriptionElement = articleDiv.querySelector('.description');
      const hiddenTitleField = document.getElementById('hidden_title');
      const hiddenLinkField = document.getElementById('hidden_link');
      const hiddenIssueField = document.getElementById('hidden_issue');
      const hiddenDescriptionField = document.getElementById('hidden_description');

      hiddenTitleField.value = titleElement.textContent;
      hiddenLinkField.value = linkElement.href;
      hiddenIssueField.value = '#{@issue}';
      hiddenDescriptionField.value = descriptionElement.textContent;
    }
  });